{
  "swagger": "2.0",
  "info": {
    "description": "An API for  action that is or was performed on a patient",
    "version": "1.0.0",
    "title": "Procedure API",
    "contact": {
      "email": "you@your-company.com"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    }
  },
  "host": "localhost:6547",
  "basePath": "/api/v1.0/",
  "tags": [
    {
      "name": "admins",
      "description": "Secured Admin-only calls"
    },
    {
      "name": "admins",
      "description": "Operations available to regular developers"
    }
  ],
  "schemes": [
    "https"
  ],
  "paths": {
    "/procedures": {
      "get": {
        "tags": [
          "admins"
        ],
        "summary": "searches Procedure",
        "description": "By passing in the appropriate options, you can search for\navailable Procedure in the system\n",
        "operationId": "search_procedure",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "skip",
            "in": "query",
            "description": "number of records to skip for pagination",
            "required": false,
            "type": "integer",
            "minimum": 0,
            "format": "int32"
          },
          {
            "name": "limit",
            "in": "query",
            "description": "maximum number of records to return",
            "required": false,
            "type": "integer",
            "maximum": 10,
            "minimum": 0,
            "format": "int32"
          },
          {
            "name": "status",
            "in": "query",
            "description": "fetch records with given status",
            "required": false,
            "type": "string",
            "maximum": 10,
            "minimum": 0,
            "format": "string"
          },
          {
            "name": "subject",
            "in": "query",
            "description": "fetch records having the given subject",
            "required": false,
            "type": "string",
            "maximum": 10,
            "minimum": 0,
            "format": "string"
          },
          {
            "name": "performer",
            "in": "query",
            "description": "fetch records having the given performer id",
            "required": false,
            "type": "string",
            "maximum": 10,
            "minimum": 0,
            "format": "string"
          },
          {
            "name": "patient",
            "in": "query",
            "description": "fetch records having the given patient id",
            "required": false,
            "type": "string",
            "maximum": 10,
            "minimum": 0,
            "format": "string"
          },
          {
            "name": "part-of",
            "in": "query",
            "description": "fetch records that are a part of referenced events",
            "required": false,
            "type": "string",
            "maximum": 10,
            "minimum": 0,
            "format": "string"
          },
          {
            "name": "location",
            "in": "query",
            "description": "fetch records that are of given location",
            "required": false,
            "type": "string",
            "maximum": 10,
            "minimum": 0,
            "format": "string"
          },
          {
            "name": "encounter",
            "in": "query",
            "description": "fetch records that are a of given encounter",
            "required": false,
            "type": "string",
            "maximum": 10,
            "minimum": 0,
            "format": "string"
          },
          {
            "name": "definition",
            "in": "query",
            "description": "fetch records that based on given definition",
            "required": false,
            "type": "string",
            "maximum": 10,
            "minimum": 0,
            "format": "string"
          },
          {
            "name": "context",
            "in": "query",
            "description": "fetch records  of a given context",
            "required": false,
            "type": "string",
            "maximum": 10,
            "minimum": 0,
            "format": "string"
          },
          {
            "name": "code",
            "in": "query",
            "description": "fetch records that are a of given procedure code",
            "required": false,
            "type": "string",
            "maximum": 10,
            "minimum": 0,
            "format": "string"
          },
          {
            "name": "based-on",
            "in": "query",
            "description": "fetch records that are a of given based-on object",
            "required": false,
            "type": "string",
            "maximum": 10,
            "minimum": 0,
            "format": "string"
          },
          {
            "name": "date",
            "in": "query",
            "description": "fetch records based on a given date/Period the procedure was performed",
            "required": false,
            "type": "string",
            "maximum": 10,
            "minimum": 0,
            "format": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "search results matching criteria",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/ProcedureItem"
              }
            }
          },
          "400": {
            "description": "bad input parameter"
          }
        },
        "x-swagger-router-controller": "jiva_Fhir_Api.api.procedure.controllers.procedure_controller"
      },
      "post": {
        "tags": [
          "admins"
        ],
        "summary": "adds an Procedure item",
        "description": "Adds an item to the system",
        "operationId": "add_procedure",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "ProcedureItem",
            "description": "Procedure item to add",
            "required": false,
            "schema": {
              "$ref": "#/definitions/ProcedureItem"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "item created"
          },
          "400": {
            "description": "invalid input, object invalid"
          }
        },
        "x-swagger-router-controller": "jiva_Fhir_Api.api.procedure.controllers.procedure_controller"
      },
      "put": {
        "tags": [
          "admins"
        ],
        "summary": "Update an existing ProcedureItem record",
        "operationId": "update_procedure",
        "consumes": [
          "application/json",
          "application/xml"
        ],
        "produces": [
          "application/xml",
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Procedure object that needs to be updated to the database",
            "required": true,
            "schema": {
              "$ref": "#/definitions/ProcedureItem"
            }
          }
        ],
        "responses": {
          "400": {
            "description": "Invalid Procedure ID supplied"
          },
          "404": {
            "description": "Procedure not found"
          },
          "405": {
            "description": "Validation exception"
          }
        },
        "x-swagger-router-controller": "jiva_Fhir_Api.api.procedure.controllers.procedure_controller"
      },
      "delete": {
        "tags": [
          "admins"
        ],
        "summary": "Deletes a ProcedureItem record",
        "description": "This API deletes a Procedure record based on the ProcedureIdn passed",
        "operationId": "delete_procedure",
        "produces": [
          "application/xml",
          "application/json"
        ],
        "parameters": [
          {
            "name": "ProcedureIdn",
            "in": "query",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Record deleted successfully"
          },
          "400": {
            "description": "Invalid Procedure ID supplied"
          },
          "404": {
            "description": "procedure ID not found"
          }
        },
        "x-swagger-router-controller": "jiva_Fhir_Api.api.procedure.controllers.procedure_controller"
      }
    }
  },
  "definitions": {
    "ProcedureItem": {
      "type": "object",
      "required": [
        "performer",
        "status",
        "subject"
      ],
      "properties": {
        "resourceType": {
          "type": "string"
        },
        "identifier": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Identifier"
          }
        },
        "definition": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Refrence"
          }
        },
        "basedOn": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Refrence"
          }
        },
        "partOf": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Refrence"
          }
        },
        "status": {
          "type": "string"
        },
        "notDone": {
          "type": "boolean"
        },
        "notDoneReason": {
          "$ref": "#/definitions/CodeableConcept"
        },
        "category": {
          "$ref": "#/definitions/CodeableConcept"
        },
        "code": {
          "$ref": "#/definitions/CodeableConcept"
        },
        "subject": {
          "$ref": "#/definitions/Refrence"
        },
        "context": {
          "$ref": "#/definitions/Refrence"
        },
        "performedDateTime": {
          "type": "string"
        },
        "performedPeriod": {
          "$ref": "#/definitions/Period"
        },
        "performer": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/ProcedureItem_performer"
          }
        },
        "location": {
          "$ref": "#/definitions/Refrence"
        },
        "reasonCode": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/CodeableConcept"
          }
        },
        "reasonReference": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Refrence"
          }
        },
        "bodySite": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/CodeableConcept"
          }
        },
        "outcome": {
          "$ref": "#/definitions/CodeableConcept"
        },
        "report": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Refrence"
          }
        },
        "complication": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/CodeableConcept"
          }
        },
        "complicationDetail": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Refrence"
          }
        },
        "followUp": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/CodeableConcept"
          }
        },
        "note": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Annotation"
          }
        },
        "focalDevice": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/ProcedureItem_focalDevice"
          }
        },
        "usedReference": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Refrence"
          }
        },
        "usedCode": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/CodeableConcept"
          }
        }
      },
      "example": {
        "partOf": [
          {
            "reference": "reference",
            "identifier": {
              "period": {
                "start": "start",
                "end": "end"
              },
              "system": "system",
              "use": "use",
              "assigner": {
                "reference": "reference",
                "display": "display"
              },
              "type": {
                "coding": [
                  {
                    "system": "system",
                    "code": "code",
                    "Version": "Version",
                    "userSelected": true,
                    "display": "display"
                  },
                  {
                    "system": "system",
                    "code": "code",
                    "Version": "Version",
                    "userSelected": true,
                    "display": "display"
                  }
                ],
                "text": "text"
              },
              "value": "value"
            },
            "display": "display"
          },
          {
            "reference": "reference",
            "identifier": {
              "period": {
                "start": "start",
                "end": "end"
              },
              "system": "system",
              "use": "use",
              "assigner": {
                "reference": "reference",
                "display": "display"
              },
              "type": {
                "coding": [
                  {
                    "system": "system",
                    "code": "code",
                    "Version": "Version",
                    "userSelected": true,
                    "display": "display"
                  },
                  {
                    "system": "system",
                    "code": "code",
                    "Version": "Version",
                    "userSelected": true,
                    "display": "display"
                  }
                ],
                "text": "text"
              },
              "value": "value"
            },
            "display": "display"
          }
        ],
        "note": [
          {
            "authorString": "authorString",
            "authorReference": "authorReference",
            "time": "time",
            "text": "text"
          },
          {
            "authorString": "authorString",
            "authorReference": "authorReference",
            "time": "time",
            "text": "text"
          }
        ],
        "complication": [
          {
            "coding": [
              {
                "system": "system",
                "code": "code",
                "Version": "Version",
                "userSelected": true,
                "display": "display"
              },
              {
                "system": "system",
                "code": "code",
                "Version": "Version",
                "userSelected": true,
                "display": "display"
              }
            ],
            "text": "text"
          },
          {
            "coding": [
              {
                "system": "system",
                "code": "code",
                "Version": "Version",
                "userSelected": true,
                "display": "display"
              },
              {
                "system": "system",
                "code": "code",
                "Version": "Version",
                "userSelected": true,
                "display": "display"
              }
            ],
            "text": "text"
          }
        ],
        "code": {
          "coding": [
            {
              "system": "system",
              "code": "code",
              "Version": "Version",
              "userSelected": true,
              "display": "display"
            },
            {
              "system": "system",
              "code": "code",
              "Version": "Version",
              "userSelected": true,
              "display": "display"
            }
          ],
          "text": "text"
        },
        "subject": {
          "reference": "reference",
          "identifier": {
            "period": {
              "start": "start",
              "end": "end"
            },
            "system": "system",
            "use": "use",
            "assigner": {
              "reference": "reference",
              "display": "display"
            },
            "type": {
              "coding": [
                {
                  "system": "system",
                  "code": "code",
                  "Version": "Version",
                  "userSelected": true,
                  "display": "display"
                },
                {
                  "system": "system",
                  "code": "code",
                  "Version": "Version",
                  "userSelected": true,
                  "display": "display"
                }
              ],
              "text": "text"
            },
            "value": "value"
          },
          "display": "display"
        },
        "reasonReference": [
          {
            "reference": "reference",
            "identifier": {
              "period": {
                "start": "start",
                "end": "end"
              },
              "system": "system",
              "use": "use",
              "assigner": {
                "reference": "reference",
                "display": "display"
              },
              "type": {
                "coding": [
                  {
                    "system": "system",
                    "code": "code",
                    "Version": "Version",
                    "userSelected": true,
                    "display": "display"
                  },
                  {
                    "system": "system",
                    "code": "code",
                    "Version": "Version",
                    "userSelected": true,
                    "display": "display"
                  }
                ],
                "text": "text"
              },
              "value": "value"
            },
            "display": "display"
          },
          {
            "reference": "reference",
            "identifier": {
              "period": {
                "start": "start",
                "end": "end"
              },
              "system": "system",
              "use": "use",
              "assigner": {
                "reference": "reference",
                "display": "display"
              },
              "type": {
                "coding": [
                  {
                    "system": "system",
                    "code": "code",
                    "Version": "Version",
                    "userSelected": true,
                    "display": "display"
                  },
                  {
                    "system": "system",
                    "code": "code",
                    "Version": "Version",
                    "userSelected": true,
                    "display": "display"
                  }
                ],
                "text": "text"
              },
              "value": "value"
            },
            "display": "display"
          }
        ],
        "performedPeriod": {
          "start": "start",
          "end": "end"
        },
        "followUp": [
          {
            "coding": [
              {
                "system": "system",
                "code": "code",
                "Version": "Version",
                "userSelected": true,
                "display": "display"
              },
              {
                "system": "system",
                "code": "code",
                "Version": "Version",
                "userSelected": true,
                "display": "display"
              }
            ],
            "text": "text"
          },
          {
            "coding": [
              {
                "system": "system",
                "code": "code",
                "Version": "Version",
                "userSelected": true,
                "display": "display"
              },
              {
                "system": "system",
                "code": "code",
                "Version": "Version",
                "userSelected": true,
                "display": "display"
              }
            ],
            "text": "text"
          }
        ],
        "context": {
          "reference": "reference",
          "identifier": {
            "period": {
              "start": "start",
              "end": "end"
            },
            "system": "system",
            "use": "use",
            "assigner": {
              "reference": "reference",
              "display": "display"
            },
            "type": {
              "coding": [
                {
                  "system": "system",
                  "code": "code",
                  "Version": "Version",
                  "userSelected": true,
                  "display": "display"
                },
                {
                  "system": "system",
                  "code": "code",
                  "Version": "Version",
                  "userSelected": true,
                  "display": "display"
                }
              ],
              "text": "text"
            },
            "value": "value"
          },
          "display": "display"
        },
        "definition": [
          {
            "reference": "reference",
            "identifier": {
              "period": {
                "start": "start",
                "end": "end"
              },
              "system": "system",
              "use": "use",
              "assigner": {
                "reference": "reference",
                "display": "display"
              },
              "type": {
                "coding": [
                  {
                    "system": "system",
                    "code": "code",
                    "Version": "Version",
                    "userSelected": true,
                    "display": "display"
                  },
                  {
                    "system": "system",
                    "code": "code",
                    "Version": "Version",
                    "userSelected": true,
                    "display": "display"
                  }
                ],
                "text": "text"
              },
              "value": "value"
            },
            "display": "display"
          },
          {
            "reference": "reference",
            "identifier": {
              "period": {
                "start": "start",
                "end": "end"
              },
              "system": "system",
              "use": "use",
              "assigner": {
                "reference": "reference",
                "display": "display"
              },
              "type": {
                "coding": [
                  {
                    "system": "system",
                    "code": "code",
                    "Version": "Version",
                    "userSelected": true,
                    "display": "display"
                  },
                  {
                    "system": "system",
                    "code": "code",
                    "Version": "Version",
                    "userSelected": true,
                    "display": "display"
                  }
                ],
                "text": "text"
              },
              "value": "value"
            },
            "display": "display"
          }
        ],
        "usedCode": [
          {
            "coding": [
              {
                "system": "system",
                "code": "code",
                "Version": "Version",
                "userSelected": true,
                "display": "display"
              },
              {
                "system": "system",
                "code": "code",
                "Version": "Version",
                "userSelected": true,
                "display": "display"
              }
            ],
            "text": "text"
          },
          {
            "coding": [
              {
                "system": "system",
                "code": "code",
                "Version": "Version",
                "userSelected": true,
                "display": "display"
              },
              {
                "system": "system",
                "code": "code",
                "Version": "Version",
                "userSelected": true,
                "display": "display"
              }
            ],
            "text": "text"
          }
        ],
        "reasonCode": [
          {
            "coding": [
              {
                "system": "system",
                "code": "code",
                "Version": "Version",
                "userSelected": true,
                "display": "display"
              },
              {
                "system": "system",
                "code": "code",
                "Version": "Version",
                "userSelected": true,
                "display": "display"
              }
            ],
            "text": "text"
          },
          {
            "coding": [
              {
                "system": "system",
                "code": "code",
                "Version": "Version",
                "userSelected": true,
                "display": "display"
              },
              {
                "system": "system",
                "code": "code",
                "Version": "Version",
                "userSelected": true,
                "display": "display"
              }
            ],
            "text": "text"
          }
        ],
        "performedDateTime": "performedDateTime",
        "basedOn": [
          {
            "reference": "reference",
            "identifier": {
              "period": {
                "start": "start",
                "end": "end"
              },
              "system": "system",
              "use": "use",
              "assigner": {
                "reference": "reference",
                "display": "display"
              },
              "type": {
                "coding": [
                  {
                    "system": "system",
                    "code": "code",
                    "Version": "Version",
                    "userSelected": true,
                    "display": "display"
                  },
                  {
                    "system": "system",
                    "code": "code",
                    "Version": "Version",
                    "userSelected": true,
                    "display": "display"
                  }
                ],
                "text": "text"
              },
              "value": "value"
            },
            "display": "display"
          },
          {
            "reference": "reference",
            "identifier": {
              "period": {
                "start": "start",
                "end": "end"
              },
              "system": "system",
              "use": "use",
              "assigner": {
                "reference": "reference",
                "display": "display"
              },
              "type": {
                "coding": [
                  {
                    "system": "system",
                    "code": "code",
                    "Version": "Version",
                    "userSelected": true,
                    "display": "display"
                  },
                  {
                    "system": "system",
                    "code": "code",
                    "Version": "Version",
                    "userSelected": true,
                    "display": "display"
                  }
                ],
                "text": "text"
              },
              "value": "value"
            },
            "display": "display"
          }
        ],
        "outcome": {
          "coding": [
            {
              "system": "system",
              "code": "code",
              "Version": "Version",
              "userSelected": true,
              "display": "display"
            },
            {
              "system": "system",
              "code": "code",
              "Version": "Version",
              "userSelected": true,
              "display": "display"
            }
          ],
          "text": "text"
        },
        "identifier": [
          {
            "period": {
              "start": "start",
              "end": "end"
            },
            "system": "system",
            "use": "use",
            "assigner": {
              "reference": "reference",
              "display": "display"
            },
            "type": {
              "coding": [
                {
                  "system": "system",
                  "code": "code",
                  "Version": "Version",
                  "userSelected": true,
                  "display": "display"
                },
                {
                  "system": "system",
                  "code": "code",
                  "Version": "Version",
                  "userSelected": true,
                  "display": "display"
                }
              ],
              "text": "text"
            },
            "value": "value"
          },
          {
            "period": {
              "start": "start",
              "end": "end"
            },
            "system": "system",
            "use": "use",
            "assigner": {
              "reference": "reference",
              "display": "display"
            },
            "type": {
              "coding": [
                {
                  "system": "system",
                  "code": "code",
                  "Version": "Version",
                  "userSelected": true,
                  "display": "display"
                },
                {
                  "system": "system",
                  "code": "code",
                  "Version": "Version",
                  "userSelected": true,
                  "display": "display"
                }
              ],
              "text": "text"
            },
            "value": "value"
          }
        ],
        "performer": [
          {
            "actor": {
              "reference": "reference",
              "identifier": {
                "period": {
                  "start": "start",
                  "end": "end"
                },
                "system": "system",
                "use": "use",
                "assigner": {
                  "reference": "reference",
                  "display": "display"
                },
                "type": {
                  "coding": [
                    {
                      "system": "system",
                      "code": "code",
                      "Version": "Version",
                      "userSelected": true,
                      "display": "display"
                    },
                    {
                      "system": "system",
                      "code": "code",
                      "Version": "Version",
                      "userSelected": true,
                      "display": "display"
                    }
                  ],
                  "text": "text"
                },
                "value": "value"
              },
              "display": "display"
            },
            "role": {
              "coding": [
                {
                  "system": "system",
                  "code": "code",
                  "Version": "Version",
                  "userSelected": true,
                  "display": "display"
                },
                {
                  "system": "system",
                  "code": "code",
                  "Version": "Version",
                  "userSelected": true,
                  "display": "display"
                }
              ],
              "text": "text"
            },
            "onBehalfOf": {
              "reference": "reference",
              "identifier": {
                "period": {
                  "start": "start",
                  "end": "end"
                },
                "system": "system",
                "use": "use",
                "assigner": {
                  "reference": "reference",
                  "display": "display"
                },
                "type": {
                  "coding": [
                    {
                      "system": "system",
                      "code": "code",
                      "Version": "Version",
                      "userSelected": true,
                      "display": "display"
                    },
                    {
                      "system": "system",
                      "code": "code",
                      "Version": "Version",
                      "userSelected": true,
                      "display": "display"
                    }
                  ],
                  "text": "text"
                },
                "value": "value"
              },
              "display": "display"
            }
          },
          {
            "actor": {
              "reference": "reference",
              "identifier": {
                "period": {
                  "start": "start",
                  "end": "end"
                },
                "system": "system",
                "use": "use",
                "assigner": {
                  "reference": "reference",
                  "display": "display"
                },
                "type": {
                  "coding": [
                    {
                      "system": "system",
                      "code": "code",
                      "Version": "Version",
                      "userSelected": true,
                      "display": "display"
                    },
                    {
                      "system": "system",
                      "code": "code",
                      "Version": "Version",
                      "userSelected": true,
                      "display": "display"
                    }
                  ],
                  "text": "text"
                },
                "value": "value"
              },
              "display": "display"
            },
            "role": {
              "coding": [
                {
                  "system": "system",
                  "code": "code",
                  "Version": "Version",
                  "userSelected": true,
                  "display": "display"
                },
                {
                  "system": "system",
                  "code": "code",
                  "Version": "Version",
                  "userSelected": true,
                  "display": "display"
                }
              ],
              "text": "text"
            },
            "onBehalfOf": {
              "reference": "reference",
              "identifier": {
                "period": {
                  "start": "start",
                  "end": "end"
                },
                "system": "system",
                "use": "use",
                "assigner": {
                  "reference": "reference",
                  "display": "display"
                },
                "type": {
                  "coding": [
                    {
                      "system": "system",
                      "code": "code",
                      "Version": "Version",
                      "userSelected": true,
                      "display": "display"
                    },
                    {
                      "system": "system",
                      "code": "code",
                      "Version": "Version",
                      "userSelected": true,
                      "display": "display"
                    }
                  ],
                  "text": "text"
                },
                "value": "value"
              },
              "display": "display"
            }
          }
        ],
        "complicationDetail": [
          {
            "reference": "reference",
            "identifier": {
              "period": {
                "start": "start",
                "end": "end"
              },
              "system": "system",
              "use": "use",
              "assigner": {
                "reference": "reference",
                "display": "display"
              },
              "type": {
                "coding": [
                  {
                    "system": "system",
                    "code": "code",
                    "Version": "Version",
                    "userSelected": true,
                    "display": "display"
                  },
                  {
                    "system": "system",
                    "code": "code",
                    "Version": "Version",
                    "userSelected": true,
                    "display": "display"
                  }
                ],
                "text": "text"
              },
              "value": "value"
            },
            "display": "display"
          },
          {
            "reference": "reference",
            "identifier": {
              "period": {
                "start": "start",
                "end": "end"
              },
              "system": "system",
              "use": "use",
              "assigner": {
                "reference": "reference",
                "display": "display"
              },
              "type": {
                "coding": [
                  {
                    "system": "system",
                    "code": "code",
                    "Version": "Version",
                    "userSelected": true,
                    "display": "display"
                  },
                  {
                    "system": "system",
                    "code": "code",
                    "Version": "Version",
                    "userSelected": true,
                    "display": "display"
                  }
                ],
                "text": "text"
              },
              "value": "value"
            },
            "display": "display"
          }
        ],
        "usedReference": [
          {
            "reference": "reference",
            "identifier": {
              "period": {
                "start": "start",
                "end": "end"
              },
              "system": "system",
              "use": "use",
              "assigner": {
                "reference": "reference",
                "display": "display"
              },
              "type": {
                "coding": [
                  {
                    "system": "system",
                    "code": "code",
                    "Version": "Version",
                    "userSelected": true,
                    "display": "display"
                  },
                  {
                    "system": "system",
                    "code": "code",
                    "Version": "Version",
                    "userSelected": true,
                    "display": "display"
                  }
                ],
                "text": "text"
              },
              "value": "value"
            },
            "display": "display"
          },
          {
            "reference": "reference",
            "identifier": {
              "period": {
                "start": "start",
                "end": "end"
              },
              "system": "system",
              "use": "use",
              "assigner": {
                "reference": "reference",
                "display": "display"
              },
              "type": {
                "coding": [
                  {
                    "system": "system",
                    "code": "code",
                    "Version": "Version",
                    "userSelected": true,
                    "display": "display"
                  },
                  {
                    "system": "system",
                    "code": "code",
                    "Version": "Version",
                    "userSelected": true,
                    "display": "display"
                  }
                ],
                "text": "text"
              },
              "value": "value"
            },
            "display": "display"
          }
        ],
        "focalDevice": [
          {
            "action": {
              "coding": [
                {
                  "system": "system",
                  "code": "code",
                  "Version": "Version",
                  "userSelected": true,
                  "display": "display"
                },
                {
                  "system": "system",
                  "code": "code",
                  "Version": "Version",
                  "userSelected": true,
                  "display": "display"
                }
              ],
              "text": "text"
            },
            "manipulated": {
              "reference": "reference",
              "identifier": {
                "period": {
                  "start": "start",
                  "end": "end"
                },
                "system": "system",
                "use": "use",
                "assigner": {
                  "reference": "reference",
                  "display": "display"
                },
                "type": {
                  "coding": [
                    {
                      "system": "system",
                      "code": "code",
                      "Version": "Version",
                      "userSelected": true,
                      "display": "display"
                    },
                    {
                      "system": "system",
                      "code": "code",
                      "Version": "Version",
                      "userSelected": true,
                      "display": "display"
                    }
                  ],
                  "text": "text"
                },
                "value": "value"
              },
              "display": "display"
            }
          },
          {
            "action": {
              "coding": [
                {
                  "system": "system",
                  "code": "code",
                  "Version": "Version",
                  "userSelected": true,
                  "display": "display"
                },
                {
                  "system": "system",
                  "code": "code",
                  "Version": "Version",
                  "userSelected": true,
                  "display": "display"
                }
              ],
              "text": "text"
            },
            "manipulated": {
              "reference": "reference",
              "identifier": {
                "period": {
                  "start": "start",
                  "end": "end"
                },
                "system": "system",
                "use": "use",
                "assigner": {
                  "reference": "reference",
                  "display": "display"
                },
                "type": {
                  "coding": [
                    {
                      "system": "system",
                      "code": "code",
                      "Version": "Version",
                      "userSelected": true,
                      "display": "display"
                    },
                    {
                      "system": "system",
                      "code": "code",
                      "Version": "Version",
                      "userSelected": true,
                      "display": "display"
                    }
                  ],
                  "text": "text"
                },
                "value": "value"
              },
              "display": "display"
            }
          }
        ],
        "notDone": true,
        "bodySite": [
          {
            "coding": [
              {
                "system": "system",
                "code": "code",
                "Version": "Version",
                "userSelected": true,
                "display": "display"
              },
              {
                "system": "system",
                "code": "code",
                "Version": "Version",
                "userSelected": true,
                "display": "display"
              }
            ],
            "text": "text"
          },
          {
            "coding": [
              {
                "system": "system",
                "code": "code",
                "Version": "Version",
                "userSelected": true,
                "display": "display"
              },
              {
                "system": "system",
                "code": "code",
                "Version": "Version",
                "userSelected": true,
                "display": "display"
              }
            ],
            "text": "text"
          }
        ],
        "report": [
          {
            "reference": "reference",
            "identifier": {
              "period": {
                "start": "start",
                "end": "end"
              },
              "system": "system",
              "use": "use",
              "assigner": {
                "reference": "reference",
                "display": "display"
              },
              "type": {
                "coding": [
                  {
                    "system": "system",
                    "code": "code",
                    "Version": "Version",
                    "userSelected": true,
                    "display": "display"
                  },
                  {
                    "system": "system",
                    "code": "code",
                    "Version": "Version",
                    "userSelected": true,
                    "display": "display"
                  }
                ],
                "text": "text"
              },
              "value": "value"
            },
            "display": "display"
          },
          {
            "reference": "reference",
            "identifier": {
              "period": {
                "start": "start",
                "end": "end"
              },
              "system": "system",
              "use": "use",
              "assigner": {
                "reference": "reference",
                "display": "display"
              },
              "type": {
                "coding": [
                  {
                    "system": "system",
                    "code": "code",
                    "Version": "Version",
                    "userSelected": true,
                    "display": "display"
                  },
                  {
                    "system": "system",
                    "code": "code",
                    "Version": "Version",
                    "userSelected": true,
                    "display": "display"
                  }
                ],
                "text": "text"
              },
              "value": "value"
            },
            "display": "display"
          }
        ],
        "notDoneReason": {
          "coding": [
            {
              "system": "system",
              "code": "code",
              "Version": "Version",
              "userSelected": true,
              "display": "display"
            },
            {
              "system": "system",
              "code": "code",
              "Version": "Version",
              "userSelected": true,
              "display": "display"
            }
          ],
          "text": "text"
        },
        "location": {
          "reference": "reference",
          "identifier": {
            "period": {
              "start": "start",
              "end": "end"
            },
            "system": "system",
            "use": "use",
            "assigner": {
              "reference": "reference",
              "display": "display"
            },
            "type": {
              "coding": [
                {
                  "system": "system",
                  "code": "code",
                  "Version": "Version",
                  "userSelected": true,
                  "display": "display"
                },
                {
                  "system": "system",
                  "code": "code",
                  "Version": "Version",
                  "userSelected": true,
                  "display": "display"
                }
              ],
              "text": "text"
            },
            "value": "value"
          },
          "display": "display"
        },
        "category": {
          "coding": [
            {
              "system": "system",
              "code": "code",
              "Version": "Version",
              "userSelected": true,
              "display": "display"
            },
            {
              "system": "system",
              "code": "code",
              "Version": "Version",
              "userSelected": true,
              "display": "display"
            }
          ],
          "text": "text"
        },
        "resourceType": "resourceType",
        "status": "status"
      }
    },
    "Identifier": {
      "type": "object",
      "properties": {
        "use": {
          "type": "string"
        },
        "type": {
          "$ref": "#/definitions/Identifier_type"
        },
        "system": {
          "type": "string"
        },
        "value": {
          "type": "string"
        },
        "period": {
          "$ref": "#/definitions/Identifier_period"
        },
        "assigner": {
          "$ref": "#/definitions/Identifier_assigner"
        }
      },
      "example": {
        "period": {
          "start": "start",
          "end": "end"
        },
        "system": "system",
        "use": "use",
        "assigner": {
          "reference": "reference",
          "display": "display"
        },
        "type": {
          "coding": [
            {
              "system": "system",
              "code": "code",
              "Version": "Version",
              "userSelected": true,
              "display": "display"
            },
            {
              "system": "system",
              "code": "code",
              "Version": "Version",
              "userSelected": true,
              "display": "display"
            }
          ],
          "text": "text"
        },
        "value": "value"
      }
    },
    "CodeableConcept": {
      "type": "object",
      "properties": {
        "coding": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Identifier_type_coding"
          }
        },
        "text": {
          "type": "string"
        }
      },
      "example": {
        "coding": [
          {
            "system": "system",
            "code": "code",
            "Version": "Version",
            "userSelected": true,
            "display": "display"
          },
          {
            "system": "system",
            "code": "code",
            "Version": "Version",
            "userSelected": true,
            "display": "display"
          }
        ],
        "text": "text"
      }
    },
    "Period": {
      "type": "object",
      "properties": {
        "start": {
          "type": "string"
        },
        "end": {
          "type": "string"
        }
      },
      "example": {
        "start": "start",
        "end": "end"
      }
    },
    "Annotation": {
      "type": "object",
      "properties": {
        "authorReference": {
          "$ref": "#/definitions/Refrence"
        },
        "authorString": {
          "type": "string"
        },
        "time": {
          "type": "string"
        },
        "text": {
          "type": "string"
        }
      },
      "example": {
        "authorString": "authorString",
        "authorReference": "authorReference",
        "time": "time",
        "text": "text"
      }
    },
    "Refrence": {
      "type": "object",
      "properties": {
        "reference": {
          "type": "string"
        },
        "identifier": {
          "$ref": "#/definitions/Identifier"
        },
        "display": {
          "type": "string"
        }
      },
      "example": {
        "reference": "reference",
        "identifier": {
          "period": {
            "start": "start",
            "end": "end"
          },
          "system": "system",
          "use": "use",
          "assigner": {
            "reference": "reference",
            "display": "display"
          },
          "type": {
            "coding": [
              {
                "system": "system",
                "code": "code",
                "Version": "Version",
                "userSelected": true,
                "display": "display"
              },
              {
                "system": "system",
                "code": "code",
                "Version": "Version",
                "userSelected": true,
                "display": "display"
              }
            ],
            "text": "text"
          },
          "value": "value"
        },
        "display": "display"
      }
    },
    "ProcedureItem_performer": {
      "properties": {
        "role": {
          "$ref": "#/definitions/CodeableConcept"
        },
        "actor": {
          "$ref": "#/definitions/Refrence"
        },
        "onBehalfOf": {
          "$ref": "#/definitions/Refrence"
        }
      },
      "example": {
        "actor": {
          "reference": "reference",
          "identifier": {
            "period": {
              "start": "start",
              "end": "end"
            },
            "system": "system",
            "use": "use",
            "assigner": {
              "reference": "reference",
              "display": "display"
            },
            "type": {
              "coding": [
                {
                  "system": "system",
                  "code": "code",
                  "Version": "Version",
                  "userSelected": true,
                  "display": "display"
                },
                {
                  "system": "system",
                  "code": "code",
                  "Version": "Version",
                  "userSelected": true,
                  "display": "display"
                }
              ],
              "text": "text"
            },
            "value": "value"
          },
          "display": "display"
        },
        "role": {
          "coding": [
            {
              "system": "system",
              "code": "code",
              "Version": "Version",
              "userSelected": true,
              "display": "display"
            },
            {
              "system": "system",
              "code": "code",
              "Version": "Version",
              "userSelected": true,
              "display": "display"
            }
          ],
          "text": "text"
        },
        "onBehalfOf": {
          "reference": "reference",
          "identifier": {
            "period": {
              "start": "start",
              "end": "end"
            },
            "system": "system",
            "use": "use",
            "assigner": {
              "reference": "reference",
              "display": "display"
            },
            "type": {
              "coding": [
                {
                  "system": "system",
                  "code": "code",
                  "Version": "Version",
                  "userSelected": true,
                  "display": "display"
                },
                {
                  "system": "system",
                  "code": "code",
                  "Version": "Version",
                  "userSelected": true,
                  "display": "display"
                }
              ],
              "text": "text"
            },
            "value": "value"
          },
          "display": "display"
        }
      }
    },
    "ProcedureItem_focalDevice": {
      "properties": {
        "action": {
          "$ref": "#/definitions/CodeableConcept"
        },
        "manipulated": {
          "$ref": "#/definitions/Refrence"
        }
      },
      "example": {
        "action": {
          "coding": [
            {
              "system": "system",
              "code": "code",
              "Version": "Version",
              "userSelected": true,
              "display": "display"
            },
            {
              "system": "system",
              "code": "code",
              "Version": "Version",
              "userSelected": true,
              "display": "display"
            }
          ],
          "text": "text"
        },
        "manipulated": {
          "reference": "reference",
          "identifier": {
            "period": {
              "start": "start",
              "end": "end"
            },
            "system": "system",
            "use": "use",
            "assigner": {
              "reference": "reference",
              "display": "display"
            },
            "type": {
              "coding": [
                {
                  "system": "system",
                  "code": "code",
                  "Version": "Version",
                  "userSelected": true,
                  "display": "display"
                },
                {
                  "system": "system",
                  "code": "code",
                  "Version": "Version",
                  "userSelected": true,
                  "display": "display"
                }
              ],
              "text": "text"
            },
            "value": "value"
          },
          "display": "display"
        }
      }
    },
    "Identifier_type_coding": {
      "properties": {
        "system": {
          "type": "string"
        },
        "Version": {
          "type": "string"
        },
        "code": {
          "type": "string"
        },
        "display": {
          "type": "string"
        },
        "userSelected": {
          "type": "boolean"
        }
      },
      "example": {
        "system": "system",
        "code": "code",
        "Version": "Version",
        "userSelected": true,
        "display": "display"
      }
    },
    "Identifier_type": {
      "properties": {
        "coding": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Identifier_type_coding"
          }
        },
        "text": {
          "type": "string"
        }
      },
      "example": {
        "coding": [
          {
            "system": "system",
            "code": "code",
            "Version": "Version",
            "userSelected": true,
            "display": "display"
          },
          {
            "system": "system",
            "code": "code",
            "Version": "Version",
            "userSelected": true,
            "display": "display"
          }
        ],
        "text": "text"
      }
    },
    "Identifier_period": {
      "properties": {
        "start": {
          "type": "string"
        },
        "end": {
          "type": "string"
        }
      },
      "example": {
        "start": "start",
        "end": "end"
      }
    },
    "Identifier_assigner": {
      "properties": {
        "reference": {
          "type": "string"
        },
        "display": {
          "type": "string"
        }
      },
      "example": {
        "reference": "reference",
        "display": "display"
      }
    }
  }
}